language: cpp
services:
  - docker
dist: xenial

script:
  - >
    docker build -t lightdb/environment -f docker/Dockerfile.environment . &&
    docker build -t lightdb/core        -f docker/Dockerfile . &&
    docker build -t lightdb/test        -f docker/Dockerfile.test .
